db.resturants.find()
db.restaurants.find({},{_id:1,name:1,borough:1,cuisine:1})
db.restaurants.find({}, {_id:0,name:1,borough:1,cuisine:1})
db.restaurants.find({}, {_id:0,name:1,borough:1,"address.zipcode":1})
db.restaurants.find({"borough": "Bronx"})
db.restaurants.find({"borough": "Bronx"}).limit(5)
db.restaurants.find({"borough": "Bronx"}).skip(5).limit(5)
db.restaurants.find({"grades.score":{$gt:90}})
db.restaurants.find({"grades": {$elemMatch: {score: {$gt:80, $lt:100}}}})
db.restaurants.find({"address.coord.0":{$lt:-95.754168}})
db.restaurants.find({$and:[{"cuisine":{$ne:"American"}},{"grades.score":{$gt:70}},{"address.coord.0":{$lt:-65.754168}}]})
db.restaurants.find({"cuisine": {$ne: "American"}, "grades.score": {$gt: 70}, "address.coord.0": {$lt: -65.754168}})
db.restaurants.find({"cuisine": {$ne: "American"}, "grades.grade": 'A', "borough": {$ne: "Brooklyn"}}).sort({"cuisine":-1})
db.restaurants.find({"name":{$regex:"^Wil"}},{"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"name": {$regex: "ces$"}},{"_id": 0, "restaurant_id":1, "name": 1, "borough": 1, "cuisine": 1})
db.restaurants.find({"name": {$regex: "Reg"}},{"_id": 0, "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1})
db.restaurants.find({"borough": "Bronx", $or: [{ "cuisine": "American"}, {"cuisine": "Chinese"}]})
db.restaurants.find({"borough": {$in: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"borough": {$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"] }},{"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1}) 
db.restaurants.find({"grades.score": {$lt: 10}},{"_id":0, "restaurant_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"cuisine": "Seafood", $nor: [{"cuisine": "American"}, {"cuisine": "Chinese"}, {"name": {$regex: "^Wil"}}]},{"_id":0, "restaurant_id":1, "name":1, "borough": 1, "cuisine": 1})
db.restaurants.find({"grades": {$elemMatch: {"grade": "A","score": 11,"date": ISODate("2014-08-11T00:00:00Z")}}},{"_id":0, "restaurant_id": 1, "name": 1, "grades": 1})

